spring.application.name=AutoCatalogAPI

# H2 Database
spring.datasource.url=jdbc:h2:mem:autocatalogdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional: para que inicialice datos SQL después de crear entidades
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
jwt.secret=12345678901234567890123456789012
jwt.expiration=86400000